#!/bin/bash
set -ex

export FROM_IMAGE=ros:noetic-ros-base
export FAIL_ON_BUILD_FAILURE=""
export TARGET_MIXINS="release ccache compile-commands clang-libcxx"

docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg FAIL_ON_BUILD_FAILURE \
    --build-arg TARGET_MIXINS \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --file ../../Dockerfile ../../.
