#!/bin/bash
set -ex

export FROM_IMAGE=ros:noetic-ros-base
export FAIL_ON_BUILD_FAILURE=""
export ROS_REPO="ros-testing"

docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg FAIL_ON_BUILD_FAILURE \
    --build-arg ROS_REPO \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --file ../../Dockerfile ../../.
