#!/bin/bash
set -ex

export FROM_IMAGE=ros:melodic-ros-base
export CATKIN_DEBS="python-catkin-tools"
export FAIL_ON_BUILD_FAILURE=""
export UPSTREAM_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"
export TARGET_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"
export DOWNSTREAM_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"
export ROS_REPO="ros"

docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg CATKIN_DEBS \
    --build-arg FAIL_ON_BUILD_FAILURE \
    --build-arg UPSTREAM_CMAKE_ARGS \
    --build-arg TARGET_CMAKE_ARGS \
    --build-arg DOWNSTREAM_CMAKE_ARGS \
    --build-arg ROS_REPO \
    --file ../../Dockerfile ../../.
