#!/bin/bash
set -ex

export FROM_IMAGE=ros:melodic-ros-base
export FAIL_ON_BUILD_FAILURE=""

docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg FAIL_ON_BUILD_FAILURE \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --file ../../Dockerfile ../../.
